repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-aws-credentials
      - id: check-private-key
      - id: no-commit-to-branch

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.3.1"
    hooks:
      - id: prettier
